// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Organizer.Models;

namespace Organizer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Organizer.Models.RecordMonth", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Difference")
                        .HasColumnType("REAL");

                    b.Property<double>("Eat")
                        .HasColumnType("REAL");

                    b.Property<double>("Home")
                        .HasColumnType("REAL");

                    b.Property<double>("Income")
                        .HasColumnType("REAL");

                    b.Property<double>("Other")
                        .HasColumnType("REAL");

                    b.Property<double>("Relaxation")
                        .HasColumnType("REAL");

                    b.Property<double>("Services")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("Transport")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("RecordMonths");
                });
#pragma warning restore 612, 618
        }
    }
}
